spring:
#  main:
#    allow-circular-references: true
  application:
    name: spring-security-demo-1
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/spring-data-demo
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 9000
subo8:
  app:
    jwtSecret: SecretKey!
    jwtExpirationMs: '9000000'